## Problem 2

In this problem we will learn some new numpy functions which will be used in the future!
These functions are highly used in many machine learning algorithms

### numpy.ones()

try creating an array of given shape, 2 and type int , with ones.

In [1]:
import numpy as np

In [2]:
# your code here
arr = np.ones(2, dtype = int)
arr

array([1, 1])

try creating an array of given shape, [3,3] and type int , with ones.

In [3]:
# your code here
arr2 = np.ones((3,3), dtype = int)
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### numpy.zeros()

try creating an array of given shape, 4 and type int , with zeros.

In [4]:
# your code here
arr3 = np.zeros(4, dtype = int)
arr3

array([0, 0, 0, 0])

try creating an array of given shape, [2,2] and type int , with zeros.

In [5]:
# your code here
arr4 = np.zeros((2,2), dtype = int)
arr4

array([[0, 0],
       [0, 0]])

Similarly, try updating the data type to float

In [6]:
# your code here
arr5 = np.zeros((2,2))
arr5

array([[0., 0.],
       [0., 0.]])

### np.dtype()

Create a datatype object of int16

In [7]:
# your code here
np.dtype(np.int16)

dtype('int16')

### numpy.concatenate()

In [8]:
import numpy as np
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 

concatenate the given two arrays into a single array along the axis 0

In [9]:
# your code here

concat1 = np.concatenate((a,b), axis = 0)
concat1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

concatenate the given two arrays into a single array along the axis 1

In [10]:
# your code here
concat2 = np.concatenate((a,b), axis = 1)
concat2

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### numpy.flatten()

In [11]:
## Flatten the given 2d numpy array into 1d array
a = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) 

In [12]:
# your code here
flat = a.flatten()
flat

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

### numpy.ravel()

similarly flatten the given previous array to 1d array using numpy.ravel()

In [13]:
# your code here
rav = a.ravel()
rav

array([1, 2, 3, 2, 4, 5, 1, 2, 3])